### ISSUE TITLE
Update to cssparser 0.28 and selectors 0.23

### ISSUE THREAD

**Issue by rillian** [brave/kuchikiki#26]
Next step, we'd like to port to the dependency versions above to match what's currently used by adblock-rust to align dependencies for brave-core. Neither of these are the latest releases, but they're on the way to being up to date and useful in the meantime.

**Comment by xtexChooser** [comment]
Has there been any progress on this?

**Comment by rillian** [comment]
There has not.

**Comment by antonok-edm** [comment]
https://github.com/brave/kuchikiki/pull/72
