### ISSUE TITLE
How to get HTML content

### ISSUE THREAD

**Issue by dr-nyt** [brave/kuchikiki#73]
Any idea how I could get the innerHTML of an element? I want to select an id and get the html of that element.

**Comment by dev-ardi** [comment]
I think you would need to parse it into a string for that.

**Comment by dr-nyt** [comment]
> I think you would need to parse it into a string for that.

Perfect that worked.
```rust
let document = kuchikiki::parse_html().one(html_string);
let selector = document.select_first("#my-content").unwrap();
println!("{:?}", selector.as_node().to_string());
```
